# 游戏基础设置
WIDTH = 480
HEIGHT = 640
FPS = 60
TITLE = 'Flappy Bird with NEAT'

# 小鸟设置
BIRD_SPEED = 100
BIRD_SPEEDY_CHANGE = 5
POSITION_X = WIDTH / 6
JUMP_DURATION = 50
GRAVITY = .3

# 障碍设置
PIPE_GAP_UPBOUND = 200
PIPE_GAP_LOWBOUND = 100